name: MyEssentials
author: '@kilianevers'
version: '${project.version}'
main: de.couldbeworse.myessentials.MyEssentials
api-version: '1.20'


commands:


  #
  #   Workshops
  #

  anvil:
    description: Open a anvil from anywhere. - /anvil

  enchantmenttable:
    description: Open a enchantmenttable from anywhere. - /enchantmenttable

  cartography:
    description: Open a cartography from anywhere. - /cartography

  loom:
    description: Open a loom from anywhere. - /loom

  stonecutter:
    description: Open a stonecutter from anywhere. - /stonecutter

  grindstone:
    description: Open a grindstone from anywhere. - /grindstone

  workbench:
    description: Open a workbench from anywhere. - /workbench

  smithingtable:
    description: Open a smithingtable from anywhere. - /smithingtable


  #
  #  Player Commands
  #


  help:
    description: See all commands registered. - /help

  heal:
    description: Heal yourself up. - /heal <player>

  fly:
    description: Set yourself into flight mode. - /fly

  ping:
    description: See your own ping. - /ping

  repair:
    description: Repair the item in your hand. - /repair


#
#   Moderation's Commands
#


  time:
    description: Change the time of the world. - /time <day|night>

  weather:
    description: Change the weather of the world. - /weather <sun|rain|thunder>

  clearchat:
    description: Clear the latest chat messages. - /clearchat
    aliases:
      - cc

  invsee:
    description: Lookup others inventory. - /invsee <player>

  playerinfo:
    description: See other players important information's. - /playerinfo <player>

  gm:
    description: Change your gamemode. - /gm <0|1|2|3>
    aliases:
      - gamemode

  vanish:
    description: Set yourself or another player into vanish. - /vanish <player>

  god:
    description: Set yourself or a player inseverable. - /god <player>


#
# /////////////////////////////////////////////// PERMISSIONS //////////////////////////////////////////////////////////
#


permissions:


#
#   Workshop's Permission's
#

  myessentials.command.workshops.anvil:
    default: false

  myessentials.command.workshops.enchantmenttable:
    default: false

  myessentials.command.workshops.cartography:
    default: false

  myessentials.command.workshops.loom:
    default: false

  myessentials.command.workshops.stonecutter:
    default: false

  myessentials.command.workshops.grindstone:
    default: false

  myessentials.command.workshops.workbench:
    default: false

  myessentials.command.workshops.smithingtable:
    default: false


#
#   Player Permission's
#


  myessentials.command.help:
    default: true

  myessentials.command.heal:
    default: false

  myessentials.command.fly:
    default: false

  myessentials.command.ping:
    default: true

  myessentials.command.repair:
    default: false


#
#   Moderation's Permission's
#


  myessentials.command.time:
    default: false

  myessentials.command.weather:
    default: false

  myessentials.command.clearchat:
    default: false

  myessentials.command.invsee:
    default: false

  myessentials.command.playerinfo:
    default: false


#
#   Gamemode Permission's
#


  myessentials.command.gamemode.survival:
    default: false

  myessentials.command.gamemode.creative:
    default: false

  myessentials.command.gamemode.adventure:
    default: false

  myessentials.command.gamemode.spectator:
    default: false

  myessentials.command.vanish:
    default: false

  myessentials.command.god:
    default: false