name: MyEssentials
author: '@kilianevers'
version: '0.0.2-DEV'
main: de.couldbeworse.myessentials.MyEssentials
api-version: '1.20'


commands:

  help:
    description: See all commands registered. - /help

  heal:
    description: Heal yourself up. - /heal <player>

  fly:
    description: Set yourself into flight mode. - /fly

  gm:
    description: Change your gamemode. - /gm <0|1|2|3>
    aliases:
      - gamemode

  ping:
    description: See your own ping. - /ping

  time:
    description: Change the time of the world. - /time <day|night>

  weather:
    description: Change the weather of the world. - /weather <sun|rain|thunder>

  clearchat:
    description: Clear the latest chat messages. - /clearchat
    aliases:
      - cc

  invsee:
    description: Lookup others inventory. - /invsee <player>

  playerinfo:
    description: See other players important information's. - /playerinfo <player>

  god:
    description: Set yourself or a player inseverable. - /god <player>

  feed:
    description: Feed yourself or a player. - /feed <player>

  lightning:
    description: Summon a lightning bolt to your target player. - /lightning <player>

permissions:

  myessentials.command.help:
    default: true

  myessentials.command.heal:
    default: false

  myessentials.command.fly:
    default: false

  myessentials.command.gamemode.survival:
    default: false

  myessentials.command.gamemode.creative:
    default: false

  myessentials.command.gamemode.adventure:
    default: false

  myessentials.command.gamemode.spectator:
    default: false

  myessentials.command.ping:
    default: true

  myessentials.command.time:
    default: false

  myessentials.command.weather:
    default: false

  myessentials.command.clearchat:
    default: false

  myessentials.command.god:
    default: false

  myessentials.command.feed:
    default: false

  myessentials.command.lightning:
    default: false